name: Assign Issues

on:
  issues:
    types:
      - opened

jobs:
  assign-issue:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3
        
     - name: Assign Issue
       uses: actions/labeler@v2
       with:
         repo-token: ${{ secrets.GITHUB_TOKEN }}
         assignees: asafked121
